nodeLinker: node-modules

catalog:
  # Latest is https://pkg.pr.new/sveltejs/kit/@sveltejs/kit@656ff32
  # but has a breaking change in remote forms
  "@sveltejs/kit": https://pkg.pr.new/sveltejs/kit/@sveltejs/kit@d55c91e
