ALTER TABLE "users" ADD COLUMN "google_tokens" JSONB NOT NULL DEFAULT 'null';
ALTER TABLE "users" ALTER COLUMN "google_tokens" DROP DEFAULT;

ALTER TABLE "journal_tags" ADD CONSTRAINT "journal_tags_author_id_date_fkey" FOREIGN KEY ("author_id", "date") REFERENCES "journal_entries"("author_id", "date") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "users" ADD COLUMN "email" VARCHAR(255);

DO $$
  BEGIN
    IF EXISTS
      (SELECT 1
        FROM information_schema.views
        WHERE table_schema = 'public'
        AND table_name = 'auth_users'
      )
    THEN
      UPDATE "users" SET email = auth_users.email FROM auth_users WHERE users.id = auth_users.id;
    END IF;
  END
$$;

ALTER TABLE "users" ALTER COLUMN "email" SET NOT NULL;

CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

ALTER TABLE "users" ADD COLUMN "google_id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "users" ALTER COLUMN "google_id" DROP IDENTITY;

CREATE TABLE "google_users" (
    "id" BIGSERIAL NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "tokens" JSONB NOT NULL,

    CONSTRAINT "google_users_pkey" PRIMARY KEY ("id")
);

INSERT INTO "google_users" ("id", "email", "tokens") SELECT "google_id", "email", "google_tokens" FROM "users";
ALTER TABLE "users" DROP COLUMN "google_tokens";

CREATE UNIQUE INDEX "google_users_email_key" ON "google_users"("email");

CREATE UNIQUE INDEX "users_google_id_key" ON "users"("google_id");

ALTER TABLE "users" ADD CONSTRAINT "users_google_id_fkey" FOREIGN KEY ("google_id") REFERENCES "google_users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE "sessions" (
    "google_user_id" BIGINT NOT NULL,
    "token" VARCHAR(21) NOT NULL,

    CONSTRAINT "sessions_pkey" PRIMARY KEY ("token")
);

ALTER TABLE "sessions" ADD CONSTRAINT "sessions_google_user_id_fkey" FOREIGN KEY ("google_user_id") REFERENCES "google_users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "sessions" ADD COLUMN     "expiresAt" TIMESTAMP(3) NOT NULL;

ALTER TABLE "sessions" DROP COLUMN "expiresAt",
ADD COLUMN     "expires_at" TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "google_users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sessions" ENABLE ROW LEVEL SECURITY;

SELECT setval(
  'google_users_id_seq',
  coalesce((select max(id)+1 from google_users), 1),
  false
);

ALTER TABLE "users" ADD COLUMN "language" VARCHAR(5) NOT NULL DEFAULT 'en-US';
ALTER TABLE "users" ALTER COLUMN "language" DROP DEFAULT;

ALTER TABLE "sessions" ALTER COLUMN "expires_at" DROP DEFAULT;
